version: '3.8'
services:
  backend:
    build: ./backend1
    command: npm start
    volumes:
      - .:/usr/app/backend
      - /usr/app/backend/node_modules
    ports:
      - "8080:8080"
      - "5555:5555"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - .:/usr/app/frontend
      - /usr/app/frontend/node_modules
    ports:
      - "5173:5173"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
